language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
deploy:
  provider: gae
  project: mosa-ma
  keyfile: gae.json
  verbosity: warning
  on:
    repo: jonathasbsouza/mma-api
branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_b540ddf189de_key -iv $encrypted_b540ddf189de_iv
  -in gae.json.enc -out gae.json -d
