swagger: '2.0'
info:
  description: Mosaico Music Archive API
  version: 1.0.0
  title: Mosaico Music Archive
  # put the contact info for your development or API team
  contact:
    email: jonathas@mosaicoigreja.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: all users
  description: Operations available to any signed in person

paths:
  /songs:
    get:
      tags:
      - all users
      summary: return all songs
      operationId: getSongs
      description: |
        Return all songs on the store
      produces:
      - application/json
      parameters:
      - in: query
        name: searchString
        description: pass an optional search string for looking up song repository
        required: false
        type: string
      responses:
        200:
          description: results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Song'
        400:
          description: bad input parameter
    post:
      tags:
      - admins
      summary: adds a song
      operationId: addSong
      description: Adds an song to the archive
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: song
        description: Song item to add
        schema:
          $ref: '#/definitions/Song'
      responses:
        201:
          description: song created
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
definitions:
  Song:
    type: object
    required:
    - title
    - artist
    - releaseDate
    properties:
      id:
        type: string
        format: uuid
        example: 507f1f77bcf86cd799439011
      title:
        type: string
        example: Das Auto
      artist:
        type: array
        items:
          $ref: '#/definitions/Artist'
      tags:
        type: array
        items:
          type: string
        example: ['Worship', 'Happy']
  Artist:
    required:
    - name
    properties:
      id:
        type: string
        format: uuid
        example: 507f1f77bcf86cd799439011
      name:
        type: string
        example: Stevie Steven
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /caiosouza/MosaMusicArchive/1.0.0
schemes:
 - https
# Added by API Auto Mocking Plugin
# basePath: /caiosouza/MosaicoMusicArchive/1.0.0
# Added by API Auto Mocking Plugin
basePath: /caiosouza/MosaMA/1.0.0